name = "Plotly"
uuid = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
version = "0.4.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
HTTP = "0.9"
JSON = "0.21"
PlotlyJS = "0.15, 0.16, 0.17, 0.18"
Reexport = "1.0"
julia = "1.4"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JSON", "Test"]
